config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  require "admin_constraint"
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  get "discourse/sso"
  get "discuss" => 'discourse#embed'

  resources :jobs
  resources :lab_taggings
  resources :pages, only: [:index, :show]

  get "metrics", to: "static#metrics"
  get "signin" => "sessions#new", :as => "signin"
  get "signout" => "sessions#destroy", :as => "signout"
  get "styleguide", to: "static#styleguide"
  get '/robots.txt' => 'robots#robots', :format => :txt
  get 'stats', to: 'static#stats'
  get 'version', to: 'static#version'

  resources :sessions

  constraints(WwwSubdomain) do
    get "activity" => "activities#index", :as => "activity"
    resources :featured_images
    resources :organizations, only: [:index, :show, :new, :create, :edit, :update] do
      resources :lab_organizations, controller: 'organizations/lab_organizations' do
        member do
          post :accept
        end
      end
    end

    get "verify_email(/:id)", to: "users#verify_email", as: "verify_email"

    %w(tos privacy-policy cookie-policy about choose_locale country_guess).each do |action|
      underscored = action.underscore
      get action => "static##{underscored}", as: underscored
    end

    resources :machines
    resources :brands
    resources :comments, only: [:create]

    resources :recoveries do
      collection do
        get :check_inbox
      end
    end

    ## TODO: redirect old project urls to new project urls
    get "projects" => "redirects#projects"
    get "projects/:something" => "redirects#projects"

    get "signup" => "users#new", :as => "signup"
    get "settings" => "users#edit", :as => "settings"
    get "change_password" => "users#change_password", :as => "password"
    patch "update_password" => "users#update_password"

    get "resend_verification_email" => "users#resend_verification_email"

    namespace :backstage do
      get "users/list" => "users#list"
      resources :users do
        resources :roles, controller: 'users/roles', only: [:index, :new, :create, :destroy]
      end
      resources :employees, only: [:index]
      resources :pages, expect: [:show]
      resources :organizations, only: [:index]
      resources :my_labs, only: [:index]
      resources :events, only: [:index]
      get "projects" => "redirects#projects"
      get "my_projects" => "redirects#myprojects"

      # resources :my_projects, only: [:index]
      # resources :projects, only: [:index, :destroy] do
      #   patch :visible
      #   patch :hidden
      # end
      resources :to_approve_labs, only: [:index]

      get "manager" => "labs_manager#index"

      resources :labs do
        member do
          patch :approve
          patch :reject
          patch :remove
          patch :referee_approves
          patch :referee_rejects
          get   :request_more_info, to: 'labs#edit_request_more_info'
          patch :request_more_info
          patch :referee_requests_admin_approval
          patch :admin_approves
          patch :admin_rejects
          patch :add_more_info
        end
      end

      root to: 'labs#index'
    end

    resources :employees do
      member do
        patch :approve
      end
    end

    get 'events' => 'events#index', as: 'events'

    resources :search, only: [:index]

    # Disabling projects routes now implemented in projects.fablabs.io
    # resources :projects do
    #   collection do
    #     get '/tags', action: :search
    #     get '/lab/:slug', action: :search
    #     get :map
    #     get :embed
    #   end
    #   get 'mapdata', on: :collection
    #   resources :steps do
    #     resources :links
    #   end
    # end

    resources :referee_approval_processes, only: [:destroy]
    resources :contributions, only: [:destroy]
    resources :collaborations, only: [:destroy]
    resources :documents, only: [:destroy]
    resources :facilities, only: [:destroy]

    resources :users do
      resources :favourites, only: [:create, :destroy]
      resources :grades, only: [:create, :destroy]
    end

    get "/labs/docs/:page" => "labs#docs"

    resources :labs do
      resources :events
      resources :admin_applications
      resources :role_applications
      resources :employees
      resources :academics

      get 'mapdata', on: :collection
      member do
        get :manage_admins
      end
      collection do
        get :map
        get :embed
        get :list
      end
    end

    namespace :api, defaults: { format: :json } do
      get 'me' => 'profile#show'
      
      # admin routes (for academany scripts)
      get 'users/:slug' => 'users#get_user'
      post 'users' => 'users#create_user'
      post 'users/search' => 'users#search_users'

      get 'labs' => 'labs#index'
    end

    use_doorkeeper do
      controllers :applications => 'oauth/applications'
    end

    root to: 'static#alt'

    match '*unmatched', to: 'application#error_not_found', via: :all

  end

  constraints(ApiSubdomain) do

    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end

    get '/' => 'static#api'

    scope '/0' do
      get 'me' => 'api/profile#show'
      get 'labs', to: 'api/labs#index'
      # TODO: future redirect instead of proxy
      # get 'labs', to: redirect(status: 301, path: '/api/labs', subdomain: 'www')
    end

    match '*unmatched', to: 'api/legacy#index', via: [:get, :post, :put]

  end

  get ':id' => 'redirects#show'

  get 'projects' => 'redirects#projects'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include LabsSearch
  include ProjectsOperations
  include UsersOperations

  before_action :require_login, except: :index

  def index
    @labs = search_labs(params[:query])
      .page(params['page'])
      .per(params['per'] || 7)

    #@projects = search_projects(params[:query])

    @users = search_users(params[:query])
      .page(params['page'])
      .per(params['per'] || 7)

    @results = @labs + @users

    respond_to do |format|
      format.html
    end
  end
end

app/views/search/_lab.html.haml
- cache ["v1-#{I18n.locale}", lab] do
  = content_tag_for :div, lab, class: 'media', itemscope: true, itemtype: "http://data-vocabulary.org/Organization" do
    .img.float-left
      = link_to lab do
        = image_tag lab.avatar.thumb("100x100").url, class: 'med avatar', itemprop: "logo"
    .media-body
      = link_to lab, class: 'name' do
        %span.name{itemprop: "name"}= lab
      %span.url.microdata{itemprop: "url"}= lab_url(lab, {locale: nil})
      .lab-location
        - if lab.short_address(!params[:country]).present?
          = icon "fa-solid", "location-dot"
          %span.short_address{itemprop: "addressLocality"}= lab.short_address(!params[:country])
          %span.microdata.country{itemprop: "country"}= lab.country_code
        - if lab.email.present?
          = icon "fa-solid", "envelope"
          %span.email= mail_to(lab.email, lab.email)
        - if lab.phone.present?
          = icon "fa-solid", "phone"
          %span.telephone{itemprop: "telephone"}= lab.phone
      %p.lab-blurb.truncate{itemprop: "description"}= lab.blurb

app/views/search/_project.html.haml
- cache ["v1", project] do
  = content_tag_for :div, project, class: 'media', itemscope: true do
    .img.float-left
      = link_to project.owner do
        = image_tag project.owner.avatar_url, class: 'avatar'
    .media-body
      = link_to project.title, project
      %span
        = icon "fa-solid", "location-dot"
        = link_to project.lab do
          = project.lab.name
      %p
        = truncate strip_tags(restricted_markdown(project.description)), :length => 120, :omission => "..."
        = link_to "more", project

app/views/search/_user.html.haml
= content_tag_for :div, user do
    = link_to user, user

app/views/search/all.html.haml
- title "Search"
.row.top
  .columns.large-8
    %ul.breadcrumbs
      %li= link_to Lab.to_s.pluralize, labs_path
      %li.current= link_to t("views.labs.index.all_countries"), labs_path
  .columns.large-4
    = render "header"

.row
  .columns.large-8.content
    .row
      .columns.large-12
        -# %dl.sub-nav.right.order-by
        -#   %dt Order by:
        -#   %dd= select_tag :order, ['title','title']

    - if params[:query].present?
      .search-results
        -# %button.close{type: "button", data: { dismiss: "alert"}, aria: { hidden: true}} ×
        = link_to "×", labs_path, class: 'close right'
        #{pluralize @results.size, "search result"} for
        %strong= params[:query]

    .results= render @results

  .columns.large-4.sidebar-offcanvas

app/views/search/index.html.haml
- title "Search"
.container.mt-5

  - if @labs.size > 0
    %h4 Labs
    = paginate @labs, theme: 'twitter-bootstrap-4', nav_class: "m-auto pt-3"
    .labs= render @labs

  - if @users.size > 0
    %h4.mt-4 Users
    .users= render @users
    = paginate @users, theme: 'twitter-bootstrap-4', nav_class: "m-auto pt-3"

  - if @results.empty?
    %p We could not find what you were looking for. Maybe you can try again.