config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  require "admin_constraint"
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  get "discourse/sso"
  get "discuss" => 'discourse#embed'

  resources :jobs
  resources :lab_taggings
  resources :pages, only: [:index, :show]

  get "metrics", to: "static#metrics"
  get "signin" => "sessions#new", :as => "signin"
  get "signout" => "sessions#destroy", :as => "signout"
  get "styleguide", to: "static#styleguide"
  get '/robots.txt' => 'robots#robots', :format => :txt
  get 'stats', to: 'static#stats'
  get 'version', to: 'static#version'

  resources :sessions

  constraints(WwwSubdomain) do
    get "activity" => "activities#index", :as => "activity"
    resources :featured_images
    resources :organizations, only: [:index, :show, :new, :create, :edit, :update] do
      resources :lab_organizations, controller: 'organizations/lab_organizations' do
        member do
          post :accept
        end
      end
    end

    get "verify_email(/:id)", to: "users#verify_email", as: "verify_email"

    %w(tos privacy-policy cookie-policy about choose_locale country_guess).each do |action|
      underscored = action.underscore
      get action => "static##{underscored}", as: underscored
    end

    resources :machines
    resources :brands
    resources :comments, only: [:create]

    resources :recoveries do
      collection do
        get :check_inbox
      end
    end

    ## TODO: redirect old project urls to new project urls
    get "projects" => "redirects#projects"
    get "projects/:something" => "redirects#projects"

    get "signup" => "users#new", :as => "signup"
    get "settings" => "users#edit", :as => "settings"
    get "change_password" => "users#change_password", :as => "password"
    patch "update_password" => "users#update_password"

    get "resend_verification_email" => "users#resend_verification_email"

    namespace :backstage do
      get "users/list" => "users#list"
      resources :users do
        resources :roles, controller: 'users/roles', only: [:index, :new, :create, :destroy]
      end
      resources :employees, only: [:index]
      resources :pages, expect: [:show]
      resources :organizations, only: [:index]
      resources :my_labs, only: [:index]
      resources :events, only: [:index]
      get "projects" => "redirects#projects"
      get "my_projects" => "redirects#myprojects"

      # resources :my_projects, only: [:index]
      # resources :projects, only: [:index, :destroy] do
      #   patch :visible
      #   patch :hidden
      # end
      resources :to_approve_labs, only: [:index]

      get "manager" => "labs_manager#index"

      resources :labs do
        member do
          patch :approve
          patch :reject
          patch :remove
          patch :referee_approves
          patch :referee_rejects
          get   :request_more_info, to: 'labs#edit_request_more_info'
          patch :request_more_info
          patch :referee_requests_admin_approval
          patch :admin_approves
          patch :admin_rejects
          patch :add_more_info
        end
      end

      root to: 'labs#index'
    end

    resources :employees do
      member do
        patch :approve
      end
    end

    get 'events' => 'events#index', as: 'events'

    resources :search, only: [:index]

    # Disabling projects routes now implemented in projects.fablabs.io
    # resources :projects do
    #   collection do
    #     get '/tags', action: :search
    #     get '/lab/:slug', action: :search
    #     get :map
    #     get :embed
    #   end
    #   get 'mapdata', on: :collection
    #   resources :steps do
    #     resources :links
    #   end
    # end

    resources :referee_approval_processes, only: [:destroy]
    resources :contributions, only: [:destroy]
    resources :collaborations, only: [:destroy]
    resources :documents, only: [:destroy]
    resources :facilities, only: [:destroy]

    resources :users do
      resources :favourites, only: [:create, :destroy]
      resources :grades, only: [:create, :destroy]
    end

    get "/labs/docs/:page" => "labs#docs"

    resources :labs do
      resources :events
      resources :admin_applications
      resources :role_applications
      resources :employees
      resources :academics

      get 'mapdata', on: :collection
      member do
        get :manage_admins
      end
      collection do
        get :map
        get :embed
        get :list
      end
    end

    namespace :api, defaults: { format: :json } do
      get 'me' => 'profile#show'
      
      # admin routes (for academany scripts)
      get 'users/:slug' => 'users#get_user'
      post 'users' => 'users#create_user'
      post 'users/search' => 'users#search_users'

      get 'labs' => 'labs#index'
    end

    use_doorkeeper do
      controllers :applications => 'oauth/applications'
    end

    root to: 'static#alt'

    match '*unmatched', to: 'application#error_not_found', via: :all

  end

  constraints(ApiSubdomain) do

    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end

    get '/' => 'static#api'

    scope '/0' do
      get 'me' => 'api/profile#show'
      get 'labs', to: 'api/labs#index'
      # TODO: future redirect instead of proxy
      # get 'labs', to: redirect(status: 301, path: '/api/labs', subdomain: 'www')
    end

    match '*unmatched', to: 'api/legacy#index', via: [:get, :post, :put]

  end

  get ':id' => 'redirects#show'

  get 'projects' => 'redirects#projects'
end

app/models/discourse_service/lab.rb
module DiscourseService
  class Lab < Entity
    def name
      "Discussion about #{@entity.name}"
    end

    def description
      "#{@entity.description}

This is the general thread for discussing the lab; the thread is also visible on its page at #{url}
      "
    end

    def url
      "#{ENV['FABLAB_URL']}/labs/#{@entity.slug}"
    end

    def category
      ENV['DISCOURSE_LAB_CATEGORY']
    end

    def creator
      @entity.creator
    end
  end
end

app/controllers/api/labs_controller.rb
class Api::LabsController < Api::ApiController

  def index
    @labs = Lab.with_approved_state.includes(:links)
    render json: @labs, each_serializer: LabSerializer
  end

end

app/controllers/backstage/backstage_controller.rb
class Backstage::BackstageController < ApplicationController
  before_action :require_admin

private

  def require_admin
    if current_user
      unless superadmin or referee
        return redirect_to root_url, notice: "Not authorized"
      end
    else
      return redirect_to signin_url
    end
  end

  def require_superadmin
    if current_user
      unless superadmin
        return redirect_to root_url, notice: "Not authorized"
      end
    else
      return redirect_to signin_url
    end
  end

  def superadmin
    current_user.has_role? :superadmin
  end

  def referee
    current_user.is_referee? or current_user.is_unique_referee?
  end

  def set_ransack_auth_object
    superadmin ? :superadmin : (referee ? :admin : nil)
  end
end

app/controllers/backstage/employees_controller.rb
class Backstage::EmployeesController < Backstage::BackstageController
  before_action :require_admin

  def index
    @q = Employee.ransack(params[:q], auth_object: set_ransack_auth_object)
    @q.sorts = 'id desc' if @q.sorts.empty?
    @employees = @q.result.page(params[:page]).includes(:lab, :user).where("labs.workflow_state" => 'approved').with_unverified_state.order('employees.id DESC')
  end

  private
    def require_admin
      if current_user
        unless current_user.has_role? :superadmin
          return redirect_to backstage_labs_url, notice: "Not authorized"
        end
      else
        return redirect_to signin_url
      end
    end

end

app/controllers/backstage/events_controller.rb
class Backstage::EventsController < Backstage::BackstageController

  def index
    @e = Event.ransack(params[:q])
    @events = @e.result.page(params[:page])
  end
end

app/controllers/backstage/labs_controller.rb
class Backstage::LabsController < Backstage::BackstageController
  include LabsOperations

  def index
    if current_user.has_role? :superadmin
      @q = Lab.includes(:creator).ransack(params[:q], auth_object: set_ransack_auth_object)
    elsif current_user.is_referee? or current_user.is_unique_referee?
      @q = Lab.includes(:creator).where("referee_id IN (?)",  current_user.admin_labs.map{ |u| u.resource_id }).ransack(params[:q], auth_object: set_ransack_auth_object)
    end

    @q.sorts = 'id desc' if @q.sorts.empty?
    @labs = @q.result.page(params[:page]).per(params[:per])
    #(distinct: true)
    # @labs = Lab.order(id: :desc)
  end

  def show
    @lab = Lab.friendly.find(params[:id])
  end

  def edit
    @lab = Lab.friendly.find(params[:id])
  end

  alias edit_request_more_info edit

  def update
    @lab = Lab.friendly.find(params[:id])
    if @lab.update(lab_params)
      redirect_to backstage_labs_path, notice: "Lab updated"
    else
      render :edit
    end
  end

  %w( approve
      reject
      remove
      referee_approves
      referee_rejects
      referee_requests_admin_approval
      need_more_info
    ).each do |verb|
    define_method(verb) do
      verbed = action_to_verb[verb.parameterize.underscore.to_sym]
      @lab = Lab.friendly.find(params[:id])
      if @lab.send("#{verb}!", current_user)
        lab_send_action("#{verbed}")
        lab_log_workflow_action(verb)
        redirect_to backstage_labs_path, notice: "Lab #{verbed.tr('_', ' ')}"
      else
        redirect_to backstage_lab_path(@lab), notice: "Could not #{verb} lab"
      end
    end
  end

  def request_more_info
    @lab = Lab.friendly.find(params[:id])

    if @lab.update(lab_params)
      verbed = action_to_verb[action_name.parameterize.underscore.to_sym]

      if @lab.send("#{action_name}!", current_user)
        lab_send_action("#{verbed}")
        lab_log_workflow_action(action_name)
        redirect_to backstage_labs_path, notice: "Lab #{verbed.tr('_', ' ')}"
      end
    else
      render :edit_request_more_info
    end
  end

  private
    def lab_params
      params.require(:lab).permit!
    end

end

app/controllers/backstage/labs_manager_controller.rb
class Backstage::LabsManagerController < Backstage::BackstageController
  before_action :require_superadmin
  include LabsSearch
  
  def index
    @p = Lab.includes(:creator).ransack(params[:q], auth_object: set_ransack_auth_object)
    # @labs = search_labs_admin(name).page(params['page']).per(params['per'] || 10)
    @labs = @p.result.page(params['page']).per(params['per'] || 100)
    @sql = @p.result.to_sql
  end

  def show
    @lab = Lab.friendly.find(params[:id])
  end


end

app/controllers/backstage/my_labs_controller.rb
class Backstage::MyLabsController < Backstage::BackstageController
  def index
    @q = current_user.created_labs.ransack(params[:q], auth_object: set_ransack_auth_object)

    @q.sorts = 'id desc' if @q.sorts.empty?
    @labs = @q.result.page(params[:page]).per(params[:per])
  end
end

app/controllers/backstage/my_projects_controller.rb
class Backstage::MyProjectsController < ApplicationController
  def index
    @q = current_user.created_projects.ransack(params[:q])

    @q.sorts = 'id desc' if @q.sorts.empty?
    @projects = @q.result.page(params[:page]).per(params[:per])
  end
end

app/controllers/backstage/organizations_controller.rb
class Backstage::OrganizationsController < Backstage::BackstageController

  def index
    @q = Organization.ransack(params[:q])
    @organizations = @q.result.page(params[:page])
  end
end

app/controllers/backstage/pages_controller.rb
class Backstage::PagesController < Backstage::BackstageController

  before_action :require_admin

  def index
    @pages = Page.page(params[:page]).order('position asc')
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to [:edit, :backstage, @page], notice: 'Page created'
    else
      render :new
    end
  end

  def edit
    find_page
  end

  def update
    find_page
    if @page.update(page_params)
      redirect_to [:edit, :backstage, @page], notice: 'Page updated'
    else
      render :edit
    end
  end

  def destroy
    find_page
    @page.destroy
    redirect_to [:backstage, :pages], notice: 'Page deleted'
  end

  private

  def find_page
    @page = Page.friendly.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :content, :published, :position, :slug)
  end
end

app/controllers/backstage/projects_controller.rb
class Backstage::ProjectsController < ApplicationController
  def index
    @projects = Project.all.includes(:owner, :lab).order(title: :asc)
      .page(params[:page]).per(params[:per])
  end

  def visibility
    @project = Project.find(params[:project_id])

    @project.visibility = action_name
    @project.save!

    redirect_to backstage_projects_path
  end

  alias visible visibility
  alias hidden  visibility

  def destroy
    @project = Project.find(params[:id])

    @project.destroy

    redirect_to :back
  end
end

app/controllers/backstage/redirects_controller.rb
class Backstage::RedirectsController < Backstage::BackstageController

  def projects
    redirect_to 'https://projects.fablabs.io', status: 302
  end

  def myprojects
    redirect_to 'https://projects.fablabs.io/@' + current_user.username , status: 302
  end
end

app/controllers/backstage/to_approve_labs_controller.rb
class Backstage::ToApproveLabsController < Backstage::BackstageController
  before_action :require_login

  def index
    @q = Lab.where(id: current_user.referee_labs.map(&:id)).ransack(params[:q], auth_object: set_ransack_auth_object)

    @q.sorts = 'id desc' if @q.sorts.empty?
    @labs = @q.result.page(params[:page]).per(params[:per])
  end
end

app/controllers/backstage/users/roles_controller.rb
class Backstage::Users::RolesController < Backstage::BackstageController
  before_action :require_superadmin
  before_action :find_user

  def index
    @roles = @user.roles
  end

  def new
    @role = @user.roles.build
  end

  def create
    @user.add_role(params[:role][:name])
    redirect_to [:backstage, @user, :roles], notice: 'Added role'
  end

  def destroy
    @role = @user.roles.find(params[:id])
    @user.remove_role(@role.name)
    redirect_to [:backstage, @user, :roles], notice: 'Removed role'
  end

  private

  def role_params
    params.require(:role).permit(:name)
  end

  def find_user
    @user = User.friendly.find(params[:user_id])
  end
end

app/controllers/backstage/users_controller.rb
class Backstage::UsersController < Backstage::BackstageController
  before_action :require_admin

  def index
    @q = User.ransack(params[:q], auth_object: set_ransack_auth_object)
    @q.sorts = 'id desc' if @q.sorts.empty?
    @users = @q.result.page(params[:page])
  end

  def show
    @user = User.friendly.find(params[:id])
  end

  def edit
    @user = User.friendly.find(params[:id])
  end

  def update
    @user = User.friendly.find(params[:id])
    if @user.update user_params
      redirect_to backstage_users_path, notice: "User updated"
    else
      render :edit
    end
  end

  def list
    @users = User.all.map { |e| "#{e.full_name} - #{e.email}" }
    render plain: @users.to_csv
  end

private

  def user_params
    params.require(:user).permit!
  end


  def require_admin
    if current_user
      unless current_user.has_role? :superadmin
        return redirect_to backstage_labs_url, notice: "Not authorized"
      end
    else
      return redirect_to signin_url
    end
  end

end

app/helpers/backstage/my_labs_helper.rb
module Backstage::MyLabsHelper
end

app/helpers/backstage/to_approve_labs_helper.rb
module Backstage::ToApproveLabsHelper
end

app/views/backstage/labs/_labs.html.haml
.container.mx-auto.well.m-3
  = title "Labs"
  = search_form_for @q, url: url_form, builder: SimpleForm::FormBuilder do |f|
    = f.input :name_or_city_cont, label: "Name"
    =# f.input :discourse_id_not_null, as: :select, collection: [:true, :false], include_blank: "Either one", label: "With discourse ID"
    =# f.input :discourse_id_null, as: :select, collection: [:true, :false], include_blank: "Either one",label: "Without discourse ID"
    =# f.input :discourse_errors_not_null, as: :select, collection: [:true, :false], include_blank: "Either one", label: "With discourse sync errors"
    .row
      .col-lg-4
        = f.input :country_code_eq, as: 'country', label: 'Country', iso_codes: true, include_blank: 'ALL'
      .col-lg-4
        = f.input :workflow_state_eq, collection: Lab.workflow_spec.state_names, label: "State", include_blank: 'ALL'
      .col-lg-4.m-auto
        = f.input :is_referee_true, as: :select, collection: [:true, :false], include_blank: "Either one"

    = f.submit "Filter", class: 'btn btn-primary'

%p.m-3= page_entries_info @labs
%table.table.table-hover
  %thead
    %tr
      %th= sort_link @q, :id, 'ID'
      %th= sort_link @q, :name, 'Name'
      %th= sort_link @q, :is_referee
      %th Country
      %th Nr of employees
      %th
        Creator
        = sort_link @q, 'creator_first_name', 'First'
        = sort_link @q, 'creator_last_name', 'Last'

      %th= sort_link @q, :state, 'State'
      %th= sort_link @q, :activity_status
  %tbody
    - @labs.each do |lab|
      = content_tag_for :tr, lab, {class: lab.current_state} do
        %td= lab.id
        %td= link_to lab, backstage_lab_path(lab)
        %td{class: ('text-green' if lab.is_referee)}= lab.is_referee
        %td= lab.country&.common_name
        %td= lab.employees.count
        %td= link_to lab.creator, lab.creator
        %td= lab.current_state
        %td= lab.activity_status

= paginate @labs, theme: 'twitter-bootstrap-4', nav_class: "m-auto p-3"

app/views/backstage/labs/edit.html.haml
= render "backstage/header"

.container
  = title "Editing #{@lab}"
  = simple_form_for [:backstage, @lab] do |f|
    = render "form_errors", resource: @lab

    %fieldset
      .text-large Basic Details
      %h5
        Name, description and slug of your Lab
      = f.input :name
      = f.input :blurb
      = f.input :description
      = f.input :slug
      %h5
        Kind of Lab
      .hint
        What kind of Fab Lab is your Lab?
        .row
        - Lab::kinds.each do |value, index|
          .col-lg-2
            %span.form-check.mb-0.mt-3
              %div.form-check-input.mt-0
                = f.radio_button :kind, value
              %label.radio.form-check-label{style: "width: 160px;"}
                = value.humanize.titleize

    %fieldset
      .text-large
        Approval process
      %h5
        Referee Labs
        .hint.px-0
          These are your Referee Labs. Please contact them in case you have any question regarding your approval process.
          .selections.referees
            - @lab.referee_approval_processes.each do |c|
              - if c.referee_lab.present? and c.id
                .col-lg-4
                  %p
                    = image_tag c.referee_lab.avatar.thumb('90x90#').url, class: 'avatar tiny center-block'
                  %p
                    = link_to link_to c.referee_lab, c.referee_lab


    %fieldset
      .text-large Status and history of your Lab
      %h5
        Current status of your Lab
        .hint.px-0
          Is this Lab already open, planned or closed?

          .row
          - Lab::ACTIVITY_STATUS.each do |status|
            .col-lg-2
              %span.form-check.mb-0.mt-3
                %div.form-check-input.mt-0
                  = f.radio_button :activity_status, status, class: 'activity-status-radio'
                %label.form-check-label.radio{style: "width: 160px;"}
                  = status.humanize.titleize


          %h5.mt-2
            History of your Lab
          .hint.px-0
            Please indicate these important dates in the history of your Lab:
          .row.pl-0.mx-0
            = f.input :activity_start_at, label: 'When did you start designing and planning your Lab?', as: 'string', input_html: {class: 'flatpickr' }
          .row.pl-0.mx-0
            = f.input :activity_inaugurated_at, label: 'When was the Lab officially inaugurated?', as: 'string', input_html: {class: 'flatpickr' }
          .row.pl-0.mx-0
            = f.input :activity_closed_at, label: 'When was the Lab closed?', as: 'string', input_html: {class: 'flatpickr' }

    %fieldset
      .text-large Location
      = f.input :address_1
      = f.input :address_2
      = f.input :city
      = f.input :county
      = f.input :postal_code
      = f.input :country_code, as: 'country', label: 'Country', iso_codes: true
      = f.input :latitude
      = f.input :longitude
      = f.input :zoom
      = f.input :address_notes

    %fieldset
      .text-large Capabilities
      = f.input :tools_list

    %fieldset
      .text-large Contact information
      = f.input :phone
      = f.input :email

    %fieldset
      .text-large Notes
      = f.input :application_notes

    %fieldset
      .text-large Referee status
      .form-check
        = f.input :is_referee, input_html: { class: 'form-check-input' }

    = f.submit 'Save', class: 'btn btn-primary btn-lg mt-4'

app/views/backstage/labs/edit_request_more_info.html.haml
= render "backstage/header"

.container
  = title "Editing #{@lab}"
  = simple_form_for [:backstage, @lab], url: request_more_info_backstage_lab_path do |f|
    = render "form_errors", resource: @lab

    %fieldset
      %legend
        Approval process
      .row
        .col-lg-12
          %p
            = f.input :improve_approval_application,
              input_html: { value: improve_approval_application_default_value(@lab) }

    .row
      .col-lg-12
        = f.submit 'Save', class: 'btn btn-primary btn-lg mt-4'

app/views/backstage/labs/index.html.haml
= render "backstage/header"

= render 'backstage/labs/labs', q: @q, url_form: [:backstage, :labs], labs: @labs

app/views/backstage/labs/show.html.haml
- if current_user.present?
  = render "backstage/header"

.container.mt-4
  .row
    .col-lg-12
      = title @lab
      %table.table
        %tr
          %th State
          %td
            = @lab.current_state

        %tr
          %th State actions
          %td
            - if current_user.present?
              - @lab.current_state.events.keys.each do |event|
                - if current_user.is_referee? || current_user.is_unique_referee? || current_user.has_role?(:superadmin)
                  - if 'request_more_info' == event.to_s
                    = button_to "#{event.capitalize.to_s.tr('_', ' ')}",
                      { controller: 'labs', action: event },
                      method: :get,
                      class:  'btn btn-primary m-1',
                      id:     'event'

                - if current_user.is_referee? or current_user.is_unique_referee?
                  - if ['referee_approves', 'referee_requests_admin_approval', 'referee_rejects'].include? event.to_s
                    = button_to "#{event.capitalize.to_s.tr('_', ' ')}", {controller: 'labs', action: event}, method: :patch, class: 'btn btn-primary m-1', id: 'event'
                - if current_user.has_role? :superadmin
                  - if ['approve', 'reject', 'remove'].include? event.to_s
                    = button_to "#{event.capitalize.to_s.tr('_', ' ')}", {controller: 'labs', action: event}, method: :patch, class: 'btn btn-primary m-1', id: 'event'

        - if @lab.referee.present?
          %tr
            %th Referee
            %td= @lab.referee

        - if current_user.present?
          - if current_user.has_role?(:superadmin) && @lab.approval_workflow_logs.present?
            %tr
              %th Workflow Approval Logs

              %td
                %ul
                  - @lab.approval_workflow_logs.each do |log|
                    - if log.user.present? and log.lab.present?
                      %li= "#{link_to(log.user.full_name, log.user)} said <strong>#{log.workflow_state}</strong> on #{log.created_at}".html_safe
                    - else
                      %li
                        = "#{log.user_id} said #{log.workflow_state} on #{log.created_at}"
                        %small User name or lab name not shown because either one ore another does no longer exist

        - if @lab.referee_approval_processes.present?
          %tr
            %th Referees
            %td
          - @lab.referee_approval_processes.each do |c|
            - if c.referee_lab.present? and c.id
              %tr
                %th
                  = image_tag c.referee_lab.avatar.thumb("90x90#").url, class: 'avatar tiny'
                %td
                  = link_to link_to c.referee_lab, c.referee_lab
                  = c.action

        %tr
          %th Avatar
          %td= image_tag @lab.avatar.url, class: 'avatar med'

        - if @lab.header.present?
          %tr
            %th Header
            %td= image_tag @lab.header.url, class: 'avatar med'
        %tr
          %th Slug
          %td= @lab.slug
        %tr
          %th Creator
          %td= link_to @lab.creator, @lab.creator
        - if @lab.application_notes.present?
          %tr
            %th Application Notes
            %td= @lab.application_notes
        %tr
          %th Description
          %td= @lab.description
        - if @lab.links.any?
          %tr
            %th URLS
            %td
              %ul
                - @lab.links.each do |link|
                  %li= link_to link.url, link.url
        - if @lab.phone.present?
          %tr
            %th Phone
            %td= @lab.phone
        - if @lab.email.present?
          %tr
            %th Email
            %td= mail_to @lab.email, @lab.email
        %tr
          %th Address
          %td= @lab.formatted_address
        - if @lab.address_notes.present?
          %tr
            %th Address Notes
            %td= @lab.address_notes
        %tr
          %th Employees
          %td
            %ul
              - @lab.employees.each do |employee|
                = content_tag_for :li, employee do
                  = link_to employee.user, employee.user
                  = employee.job_title
        %tr
          %th Events
          %td
            %ul
              - @lab.events.each do |event|
                = content_tag_for :li, event do
                  = link_to event
        %tr
          %th Is a ref
          %td= @lab.is_referee
        %tr
          %th Created At
          %td= @lab.created_at
        %tr
          %th Updated At
          %td= @lab.updated_at
        %tr
          %th Discourse sync
          %td
            = @lab.discourse_id

            - if @lab.discourse_errors.present?
              %pre
                = @lab.discourse_errors

            = comments_script(@lab.discourse_id)

      - if current_user.present?
        - if current_user.has_role? :superadmin
          = link_to edit_backstage_lab_path(@lab), class: 'btn btn-primary my-1 mr-1' do
            = icon "fa-solid", "edit", "Edit Lab"
          = link_to lab_employees_path(@lab), class: 'btn btn-primary my-1 mr-1' do
            = icon "fa-solid", "users", t('shared.edit_employee_list', default: "Edit Employee List")
          = link_to new_lab_event_path(@lab), class: 'btn btn-primary my-1 mr-1' do
            = icon "fa-solid", "calendar-days", t('shared.add_event', default: "Add Event")